<?php

return [
    'categories' => [
        [
            'name' => 'Muñecas y Bebés',
            'slug' => 'munecas-y-bebes',
            'description' => NULL,
            'image' => NULL,
            'position' => 0,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
        ],
        [
            'name' => 'Juegos de Mesa',
            'slug' => 'juegos-de-mesa',
            'description' => NULL,
            'image' => NULL,
            'position' => 0,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
        ],
        [
            'name' => 'Figuras de Acción',
            'slug' => 'figuras-de-accion',
            'description' => NULL,
            'image' => NULL,
            'position' => 0,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
        ],
        [
            'name' => 'Didácticos y Educativos',
            'slug' => 'didacticos-y-educativos',
            'description' => NULL,
            'image' => NULL,
            'position' => 0,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
        ],
        [
            'name' => 'Vehículos y Carros',
            'slug' => 'vehiculos-y-carros',
            'description' => NULL,
            'image' => NULL,
            'position' => 0,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
        ],
        [
            'name' => 'Juguetes al Aire Libre',
            'slug' => 'juguetes-al-aire-libre',
            'description' => NULL,
            'image' => NULL,
            'position' => 0,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
        ],
        [
            'name' => 'Electrónicos',
            'slug' => 'electronicos',
            'description' => NULL,
            'image' => NULL,
            'position' => 0,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
        ],
    ],
    'brands' => [
        [
            'name' => 'LEGO',
            'slug' => 'lego',
            'description' => NULL,
            'logo' => NULL,
            'website' => NULL,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
        ],
        [
            'name' => 'Mattel',
            'slug' => 'mattel',
            'description' => NULL,
            'logo' => NULL,
            'website' => NULL,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
        ],
        [
            'name' => 'Fisher-Price',
            'slug' => 'fisher-price',
            'description' => NULL,
            'logo' => NULL,
            'website' => NULL,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
        ],
        [
            'name' => 'Hasbro',
            'slug' => 'hasbro',
            'description' => NULL,
            'logo' => NULL,
            'website' => NULL,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
        ],
        [
            'name' => 'Disney',
            'slug' => 'disney',
            'description' => NULL,
            'logo' => NULL,
            'website' => NULL,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
        ],
        [
            'name' => 'Nerf',
            'slug' => 'nerf',
            'description' => NULL,
            'logo' => NULL,
            'website' => NULL,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
        ],
        [
            'name' => 'Hot Wheels',
            'slug' => 'hot-wheels',
            'description' => NULL,
            'logo' => NULL,
            'website' => NULL,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
        ],
    ],
    'users' => [
        [
            'name' => 'Test User',
            'email' => 'test@example.com',
            'email_verified_at' => '2026-08-02 00:55:53',
            'password' => '$2y$12$9RjfSZ9ygtlwZGT.ziEg5ufRmoNWBCs1I0vealt0jL80PgrCB2o1i',
            'remember_token' => 'Dx7FK5IY07',
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
            'roles' => [
                'admin',
            ],
        ],
        [
            'name' => 'Luis',
            'email' => 'luis@gmail.com',
            'email_verified_at' => NULL,
            'password' => '$2y$12$XwVmSTD1eA.DpQc5tlIA1uvAQXraXgmCk9K724Yuymn2zT0RLBRHm',
            'remember_token' => NULL,
            'created_at' => '2026-08-02 01:41:22',
            'updated_at' => '2026-08-02 01:41:22',
            'roles' => [
                'client',
            ],
        ],
        [
            'name' => 'Nathalie',
            'email' => 'nata@gmail.com',
            'email_verified_at' => NULL,
            'password' => '$2y$12$9qqeVKUR8o7.HGyHM3wJveIlA9/LIphZCEzAp59/A2F5ujagWQY0m',
            'remember_token' => NULL,
            'created_at' => '2026-09-10 14:53:19',
            'updated_at' => '2026-09-10 14:53:19',
            'roles' => [
                'client',
            ],
        ],
    ],
    'products' => [
        [
            'name' => 'LEGO Star Wars Millennium Falcon',
            'slug' => 'lego-star-wars-millennium-falcon',
            'description' => 'El icónico Halcón Milenario de Star Wars.',
            'short_description' => NULL,
            'price' => '89.99',
            'offer_price' => NULL,
            'stock' => 8,
            'sku' => NULL,
            'age_from' => 8,
            'age_to' => 99,
            'material' => 'Plástico',
            'safety_info' => NULL,
            'is_featured' => 1,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-09-10 14:50:04',
            'category_slug' => 'figuras-de-accion',
            'brand_slug' => 'lego',
            'images' => [
                [
                    'image_path' => '/storage/products/lego-star-wars-millennium-falcon-1.svg',
                    'alt_text' => 'LEGO Star Wars Millennium Falcon - vista 1',
                    'position' => 0,
                    'is_main' => 1,
                    'created_at' => '2026-08-02 01:52:19',
                    'updated_at' => '2026-08-02 01:52:19',
                ],
                [
                    'image_path' => '/storage/products/lego-star-wars-millennium-falcon-2.svg',
                    'alt_text' => 'LEGO Star Wars Millennium Falcon - vista 2',
                    'position' => 1,
                    'is_main' => 0,
                    'created_at' => '2026-08-02 01:52:19',
                    'updated_at' => '2026-08-02 01:52:19',
                ],
            ],
            'variants' => [
                [
                    'sku' => 'LEGO-SW-XL',
                    'color' => 'Negro',
                    'size' => 'XL',
                    'stock' => 2,
                    'price_extra' => '15.00',
                    'is_active' => 1,
                    'created_at' => '2026-08-02 01:32:59',
                    'updated_at' => '2026-08-02 02:29:41',
                ],
                [
                    'sku' => 'LEGO-SW-M',
                    'color' => 'Rojo',
                    'size' => 'M',
                    'stock' => 0,
                    'price_extra' => '5.00',
                    'is_active' => 1,
                    'created_at' => '2026-08-02 01:32:59',
                    'updated_at' => '2026-08-02 01:32:59',
                ],
            ],
        ],
        [
            'name' => 'Barbie Dreamhouse',
            'slug' => 'barbie-dreamhouse',
            'description' => 'La casa de ensueño de Barbie con accesorios.',
            'short_description' => NULL,
            'price' => '449.99',
            'offer_price' => NULL,
            'stock' => 6,
            'sku' => NULL,
            'age_from' => 3,
            'age_to' => 12,
            'material' => 'Plástico y tela',
            'safety_info' => NULL,
            'is_featured' => 1,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 01:42:20',
            'category_slug' => 'munecas-y-bebes',
            'brand_slug' => 'mattel',
            'images' => [
                [
                    'image_path' => '/storage/products/barbie-dreamhouse-1.svg',
                    'alt_text' => 'Barbie Dreamhouse - vista 1',
                    'position' => 0,
                    'is_main' => 1,
                    'created_at' => '2026-08-02 01:52:19',
                    'updated_at' => '2026-08-02 01:52:19',
                ],
                [
                    'image_path' => '/storage/products/barbie-dreamhouse-2.svg',
                    'alt_text' => 'Barbie Dreamhouse - vista 2',
                    'position' => 1,
                    'is_main' => 0,
                    'created_at' => '2026-08-02 01:52:19',
                    'updated_at' => '2026-08-02 01:52:19',
                ],
            ],
            'variants' => [],
        ],
        [
            'name' => 'Hot Wheels Pista Turbo',
            'slug' => 'hot-wheels-pista-turbo',
            'description' => 'Pista de carreras con lanzadores.',
            'short_description' => NULL,
            'price' => '129.99',
            'offer_price' => NULL,
            'stock' => 34,
            'sku' => NULL,
            'age_from' => 5,
            'age_to' => 12,
            'material' => 'Metal y plástico',
            'safety_info' => NULL,
            'is_featured' => 1,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-09-10 14:35:30',
            'category_slug' => 'vehiculos-y-carros',
            'brand_slug' => 'hot-wheels',
            'images' => [
                [
                    'image_path' => '/storage/products/hot-wheels-pista-turbo-1.svg',
                    'alt_text' => 'Hot Wheels Pista Turbo - vista 1',
                    'position' => 0,
                    'is_main' => 1,
                    'created_at' => '2026-08-02 01:52:19',
                    'updated_at' => '2026-08-02 01:52:19',
                ],
                [
                    'image_path' => '/storage/products/hot-wheels-pista-turbo-2.svg',
                    'alt_text' => 'Hot Wheels Pista Turbo - vista 2',
                    'position' => 1,
                    'is_main' => 0,
                    'created_at' => '2026-08-02 01:52:19',
                    'updated_at' => '2026-08-02 01:52:19',
                ],
            ],
            'variants' => [
                [
                    'sku' => 'HW-TURBO-ROJO',
                    'color' => 'Rojo',
                    'size' => NULL,
                    'stock' => 11,
                    'price_extra' => '0.00',
                    'is_active' => 1,
                    'created_at' => '2026-08-02 01:52:19',
                    'updated_at' => '2026-08-02 02:09:07',
                ],
                [
                    'sku' => 'HW-TURBO-AZUL',
                    'color' => 'Azul',
                    'size' => NULL,
                    'stock' => 10,
                    'price_extra' => '0.00',
                    'is_active' => 1,
                    'created_at' => '2026-08-02 01:52:19',
                    'updated_at' => '2026-08-02 01:52:19',
                ],
            ],
        ],
        [
            'name' => 'Nerf Elite Blaster',
            'slug' => 'nerf-elite-blaster',
            'description' => 'Pistola Nerf de alta potencia.',
            'short_description' => NULL,
            'price' => '89.99',
            'offer_price' => NULL,
            'stock' => 25,
            'sku' => NULL,
            'age_from' => 6,
            'age_to' => 14,
            'material' => 'Plástico y espuma',
            'safety_info' => NULL,
            'is_featured' => 1,
            'is_active' => 1,
            'created_at' => '2026-08-02 00:55:53',
            'updated_at' => '2026-08-02 00:55:53',
            'category_slug' => 'juguetes-al-aire-libre',
            'brand_slug' => 'nerf',
            'images' => [
                [
                    'image_path' => '/storage/products/nerf-elite-blaster-1.svg',
                    'alt_text' => 'Nerf Elite Blaster - vista 1',
                    'position' => 0,
                    'is_main' => 1,
                    'created_at' => '2026-08-02 01:52:19',
                    'updated_at' => '2026-08-02 01:52:19',
                ],
                [
                    'image_path' => '/storage/products/nerf-elite-blaster-2.svg',
                    'alt_text' => 'Nerf Elite Blaster - vista 2',
                    'position' => 1,
                    'is_main' => 0,
                    'created_at' => '2026-08-02 01:52:19',
                    'updated_at' => '2026-08-02 01:52:19',
                ],
            ],
            'variants' => [
                [
                    'sku' => 'NERF-AZUL',
                    'color' => 'Azul',
                    'size' => NULL,
                    'stock' => 10,
                    'price_extra' => '0.00',
                    'is_active' => 1,
                    'created_at' => '2026-08-02 01:52:19',
                    'updated_at' => '2026-08-02 01:52:19',
                ],
                [
                    'sku' => 'NERF-NARANJA',
                    'color' => 'Naranja',
                    'size' => NULL,
                    'stock' => 8,
                    'price_extra' => '5.00',
                    'is_active' => 1,
                    'created_at' => '2026-08-02 01:52:19',
                    'updated_at' => '2026-08-02 01:52:19',
                ],
            ],
        ],
    ],
    'orders' => [
        [
            'order_number' => 'ELGATO-5U9NEAYA',
            'subtotal' => '1799.98',
            'shipping' => '10.00',
            'total' => '1809.98',
            'status' => 'paid',
            'preference_id' => '1110867394-733cd42f-d281-42fc-906c-47684980388a',
            'payment_id' => '1327774542',
            'payment_method' => 'master',
            'paid_at' => '2026-08-02 02:28:04',
            'cancelled_at' => NULL,
            'shipping_fullname' => 'Test User',
            'shipping_phone' => '999888777',
            'shipping_address' => 'Av Test 123',
            'shipping_city' => 'Lima',
            'shipping_notes' => NULL,
            'created_at' => '2026-08-02 00:56:35',
            'updated_at' => '2026-08-02 02:28:04',
            'user_email' => 'test@example.com',
            'items' => [
                [
                    'product_name' => 'LEGO Star Wars Millennium Falcon',
                    'product_image' => NULL,
                    'unit_price' => '899.99',
                    'quantity' => 2,
                    'total' => '1799.98',
                    'color' => NULL,
                    'size' => NULL,
                    'created_at' => '2026-08-02 00:56:35',
                    'updated_at' => '2026-08-02 00:56:35',
                    'product_slug' => 'lego-star-wars-millennium-falcon',
                ],
            ],
        ],
        [
            'order_number' => 'ELGATO-STBPOTT4',
            'subtotal' => '209.98',
            'shipping' => '10.00',
            'total' => '219.98',
            'status' => 'pending',
            'preference_id' => NULL,
            'payment_id' => NULL,
            'payment_method' => NULL,
            'paid_at' => NULL,
            'cancelled_at' => NULL,
            'shipping_fullname' => 'Test User',
            'shipping_phone' => NULL,
            'shipping_address' => 'Av Test 123',
            'shipping_city' => 'Lima',
            'shipping_notes' => NULL,
            'created_at' => '2026-08-02 01:33:14',
            'updated_at' => '2026-08-02 01:33:14',
            'user_email' => 'test@example.com',
            'items' => [
                [
                    'product_name' => 'LEGO Star Wars Millennium Falcon',
                    'product_image' => NULL,
                    'unit_price' => '104.99',
                    'quantity' => 2,
                    'total' => '209.98',
                    'color' => 'Negro',
                    'size' => 'XL',
                    'created_at' => '2026-08-02 01:33:14',
                    'updated_at' => '2026-08-02 01:33:14',
                    'product_slug' => 'lego-star-wars-millennium-falcon',
                ],
            ],
        ],
        [
            'order_number' => 'ELGATO-5VKDMX8A',
            'subtotal' => '899.98',
            'shipping' => '10.00',
            'total' => '909.98',
            'status' => 'pending',
            'preference_id' => NULL,
            'payment_id' => NULL,
            'payment_method' => NULL,
            'paid_at' => NULL,
            'cancelled_at' => NULL,
            'shipping_fullname' => 'Luis',
            'shipping_phone' => '967614100',
            'shipping_address' => '51',
            'shipping_city' => 'Chancay',
            'shipping_notes' => NULL,
            'created_at' => '2026-08-02 01:42:20',
            'updated_at' => '2026-08-02 01:42:20',
            'user_email' => 'luis@gmail.com',
            'items' => [
                [
                    'product_name' => 'Barbie Dreamhouse',
                    'product_image' => NULL,
                    'unit_price' => '449.99',
                    'quantity' => 2,
                    'total' => '899.98',
                    'color' => NULL,
                    'size' => NULL,
                    'created_at' => '2026-08-02 01:42:20',
                    'updated_at' => '2026-08-02 01:42:20',
                    'product_slug' => 'barbie-dreamhouse',
                ],
            ],
        ],
        [
            'order_number' => 'ELGATO-QNFXNSTE',
            'subtotal' => '129.99',
            'shipping' => '10.00',
            'total' => '139.99',
            'status' => 'paid',
            'preference_id' => NULL,
            'payment_id' => NULL,
            'payment_method' => NULL,
            'paid_at' => NULL,
            'cancelled_at' => NULL,
            'shipping_fullname' => 'Luis',
            'shipping_phone' => '967614100',
            'shipping_address' => '51',
            'shipping_city' => 'Chancay',
            'shipping_notes' => NULL,
            'created_at' => '2026-08-02 02:09:07',
            'updated_at' => '2026-08-02 02:10:16',
            'user_email' => 'luis@gmail.com',
            'items' => [
                [
                    'product_name' => 'Hot Wheels Pista Turbo',
                    'product_image' => '/storage/products/hot-wheels-pista-turbo-1.svg',
                    'unit_price' => '129.99',
                    'quantity' => 1,
                    'total' => '129.99',
                    'color' => 'Rojo',
                    'size' => NULL,
                    'created_at' => '2026-08-02 02:09:07',
                    'updated_at' => '2026-08-02 02:09:07',
                    'product_slug' => 'hot-wheels-pista-turbo',
                ],
            ],
        ],
        [
            'order_number' => 'ELGATO-G0W4QI5N',
            'subtotal' => '104.99',
            'shipping' => '10.00',
            'total' => '114.99',
            'status' => 'pending',
            'preference_id' => '1110867394-45d8d174-6d76-423a-8324-5a5cb306aafc',
            'payment_id' => NULL,
            'payment_method' => NULL,
            'paid_at' => NULL,
            'cancelled_at' => NULL,
            'shipping_fullname' => 'Luis',
            'shipping_phone' => '967614100',
            'shipping_address' => '51',
            'shipping_city' => 'Chancay',
            'shipping_notes' => NULL,
            'created_at' => '2026-08-02 02:29:41',
            'updated_at' => '2026-08-02 02:29:43',
            'user_email' => 'luis@gmail.com',
            'items' => [
                [
                    'product_name' => 'LEGO Star Wars Millennium Falcon',
                    'product_image' => '/storage/products/lego-star-wars-millennium-falcon-1.svg',
                    'unit_price' => '104.99',
                    'quantity' => 1,
                    'total' => '104.99',
                    'color' => 'Negro',
                    'size' => 'XL',
                    'created_at' => '2026-08-02 02:29:41',
                    'updated_at' => '2026-08-02 02:29:41',
                    'product_slug' => 'lego-star-wars-millennium-falcon',
                ],
            ],
        ],
        [
            'order_number' => 'ELGATO-GUOPZRDV',
            'subtotal' => '129.99',
            'shipping' => '10.00',
            'total' => '139.99',
            'status' => 'pending',
            'preference_id' => '1110867394-914ac560-8385-463d-ac2f-d701936cae7d',
            'payment_id' => NULL,
            'payment_method' => NULL,
            'paid_at' => NULL,
            'cancelled_at' => NULL,
            'shipping_fullname' => 'Luis',
            'shipping_phone' => '+51967614100',
            'shipping_address' => '51',
            'shipping_city' => 'Chancay',
            'shipping_notes' => 'hkjjhk',
            'created_at' => '2026-09-10 14:35:30',
            'updated_at' => '2026-09-10 14:35:32',
            'user_email' => 'luis@gmail.com',
            'items' => [
                [
                    'product_name' => 'Hot Wheels Pista Turbo',
                    'product_image' => '/storage/products/hot-wheels-pista-turbo-1.svg',
                    'unit_price' => '129.99',
                    'quantity' => 1,
                    'total' => '129.99',
                    'color' => NULL,
                    'size' => NULL,
                    'created_at' => '2026-09-10 14:35:30',
                    'updated_at' => '2026-09-10 14:35:30',
                    'product_slug' => 'hot-wheels-pista-turbo',
                ],
            ],
        ],
    ],
];
